name: Update IPTV File

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 支持手动触发

jobs:
  update-iptv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # 禁用默认凭证处理

    - name: Download IPTV file
      run: |
        curl -o iptv2.m3u "https://gyssi.link/iptv/chinaiptv/%E4%BA%91%E5%8D%97%E7%9C%81.m3u?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0NDUxOTY1NjY5MjA4NDIsImlhdCI6MTczODA2MTEzMiwiZXhwIjoxNzcwODkzMTMyfQ.TP1MvqbZHzM_tgVBz0zpqApnxCiBxO_qyUd-8ivNSN0"

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add iptv2.m3u  # 先将下载的文件暂存
        
        # 检查暂存区是否有更改
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0  # 没有变化，跳过提交
        else
          git commit -m "Update iptv2.m3u file"  # 提交更改
          git pull --rebase  # 拉取最新更改并合并
          
          # 使用 Personal Access Token 进行身份验证
          git remote set-url origin https://x-access-token:${{ secrets.MY_PAT }}@github.com/wjw020206/action.git
          git push  # 推送更改
        fi